# Generated by Django 5.0.7 on 2024-09-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('salesman_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman.salesman')),
            ],
        ),
    ]
