def star(*args):
    t = args[1]
    c = args[2]
    t1 = 1
    if args[5] == 'sol':
        for i in range(0, args[0]):
            for s in list(map(lambda x: x * t, ' ')):
                t -= args[3]
            for m in list(map(lambda x: x * c, '*')):
                c += args[4]
                print(s, m, end='\n')

    if args[5] == 'sep':
        for i in range(0, args[0]):
            for s in list(map(lambda x: x * t, ' ')):
                t -= args[3]
            for m in list(map(lambda x: x * (c // 2), '*')):
                c += args[4]
            for m1 in list(map(lambda x: x * t1, ' ')):
                t1 += 6
                print(s, m, m1, m, end='\n')

star(5, 40, -1, 1, 2, 'sol')
star(3, 28, 23, -3, -6, 'sol')
star(1, 33, 13, 1, 1, 'sol')
star(3, 32, 13, 1, -4, 'sep')

print('\n' * 3)

def helkitTab(y):
    for i in range(0, 1):
        for s in list(map(lambda x: x * y, '  ')):
            print(s, end='')

def helkitSq(y):
    for i in range(0, 1):
        for s in list(map(lambda x: x * y, '██')):
            print(s, end='')

def helkitCol(y):
    for i in range(0, 1):
        for s in list(map(lambda x: x * y, '░░')):
            print(s, end='')
helkitTab(14)
helkitSq(3)
helkitTab(2)
helkitSq(3)
print()
helkitTab(3)
helkitSq(4)
helkitTab(6)
helkitSq(1)
helkitCol(3)
helkitSq(2)
helkitTab(3)
helkitSq(1)
print()
helkitTab(2)
helkitSq(1)
helkitTab(4)
helkitSq(2)
helkitTab(4)
helkitSq(1)
helkitCol(3)
helkitSq(6)
print()
helkitTab(2)
helkitSq(1)
helkitTab(6)
helkitSq(5)
helkitCol(2)
helkitSq(1)
helkitCol(2)
helkitSq(1)
helkitCol(3)
helkitSq(1)
print()
helkitTab(2)
helkitSq(1)
helkitTab(10)
helkitSq(1)
helkitCol(2)
helkitSq(1)
helkitCol(2)
helkitSq(1)
helkitCol(3)
helkitSq(1)
print()
helkitTab(2)
helkitSq(1)
helkitTab(11)
helkitSq(4)
helkitCol(1)
helkitSq(1)
helkitCol(3)
helkitSq(1)
print()
helkitTab(3)
helkitSq(2)
helkitTab(13)
helkitSq(2)
helkitCol(3)
helkitSq(1)
print()
helkitTab(3)
helkitSq(1)
helkitTab(16)
helkitSq(3)
print()
helkitTab(3)
helkitSq(1)
helkitTab(18)
helkitSq(1)
print()
helkitTab(2)
helkitSq(1)
helkitTab(19)
helkitSq(1)
print()
helkitTab(2)
helkitSq(1)
helkitTab(20)
helkitSq(1)
print()
helkitSq(4)
helkitTab(3)
helkitSq(2)
helkitTab(8)
helkitSq(2)
helkitTab(3)
helkitSq(4)
print()
helkitTab(2)
helkitSq(1)
helkitTab(4)
helkitSq(2)
helkitTab(8)
helkitSq(2)
helkitTab(4)
helkitSq(1)
print()
helkitTab(2)
helkitSq(1)
helkitTab(1)
helkitSq(1)
helkitTab(2)
helkitSq(2)
helkitTab(8)
helkitSq(2)
helkitTab(2)
helkitSq(1)
helkitTab(1)
helkitSq(1)
helkitTab(2)
print()
helkitTab(2)
helkitSq(2)
helkitTab(8)
helkitCol(2)
helkitTab(8)
helkitSq(2)
print()
helkitTab(1)
helkitSq(1)
helkitTab(1)
helkitSq(1)
helkitTab(18)
helkitSq(1)
helkitTab(1)
helkitSq(1)
print()
helkitTab(4)
helkitSq(1)
helkitTab(16)
helkitSq(1)
print()
helkitTab(3)
helkitSq(1)
helkitTab(1)
helkitSq(2)
helkitTab(12)
helkitSq(2)
helkitTab(1)
helkitSq(1)
print()
helkitTab(2)
helkitSq(1)
helkitTab(4)
helkitSq(12)
helkitTab(4)
helkitSq(1)