# Generated by Django 5.0.7 on 2024-09-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('reader_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('number', models.ImageField(unique=True, upload_to='')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
