# Generated by Django 5.0.7 on 2024-09-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('publishment', models.CharField(max_length=150)),
                ('in_library', models.BooleanField(default=bool)),
                ('reader_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readers.readers')),
            ],
        ),
    ]
