# Generated by Django 5.0.7 on 2024-09-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_reader_id_book_reader_alter_book_name_and_more'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='genres.genre'),
        ),
    ]
