# Generated by Django 5.1 on 2024-08-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1', models.IntegerField(verbose_name='Первое число')),
                ('number_2', models.IntegerField(verbose_name='Второе число')),
                ('number_3', models.IntegerField(verbose_name='Третье число')),
                ('choice', models.CharField(choices=[('min', 'Минимум из трёх'), ('max', 'Максимум из трёх'), ('avg', 'Среднеарифмитическое из трёх')], default=None, max_length=10)),
            ],
        ),
    ]
