# Generated by Django 5.0.7 on 2024-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('number', models.IntegerField(blank=True, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=150, verbose_name='E-mail')),
                ('hiring_date', models.DateTimeField(verbose_name='Дата приёма на работу')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Позиция в фирме')),
            ],
        ),
    ]
